#!/usr/bin/env php
<?php

$mypath = array_shift($argv);
$wiff_root = getenv('WIFF_ROOT');
if( $wiff_root === false ) {
  if( is_link($mypath) ) {
    $mypath = readlink($mypath);
  }
  $realpath = realpath($mypath);
  $wiff_root = dirname($realpath);
}
set_include_path(get_include_path().PATH_SEPARATOR."$wiff_root".DIRECTORY_SEPARATOR.'include');
putenv('WIFF_ROOT='.$wiff_root);

require('lib/Lib.Cli.php');

$ret = 0;
switch( $argv[0] ) {
case 'param':
  $ret = wiff_param($argv);
  break;
case 'show':
  $ret = wiff_show($argv);
  break;
case 'context':
  $ret = wiff_context($argv);
  break;
case 'help':
  $ret = wiff_help($argv);
  break;
case 'whattext':
  $ret = wiff_whattext($argv);
  break;
case 'wstart':
  $ret = wiff_wstart($argv);
  break;
case 'wstop':
  $ret = wiff_wstop($argv);
  break;
default:
  $ret = wiff_default($argv);
  break;
}

exit( $ret );

?>